service: command-bus

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-pseudo-parameters
  - serverless-localstack

package:
  exclude:
    - Dockerfile
    - package.json
    - package-lock.json
    - .gitignore
    - setup.cfg
    - config/*

custom:
  localstack:
    host: http://localhost
    endpointFile: localstack_endpoints.json

provider:
  name: aws
  region: eu-west-1
  stackName: hello-stack
  deploymentPrefix: hello-prefix
  stackTags:
    STACK_NAME: stack-name-tag
    BUILD_VERSION: build-version-tag
  tags:
    STACK_NAME: stack-name-tag
    BUILD_VERSION: build-version-tag
  stackPolicy:
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"

Resources:
  Description: "Testing Fn commands"

  Conditions:
    DevOnly:
      Fn::Equals:
        - ${opt:env_name, 'dev'}
        - dev

  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MySqsQueue

  MySnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MySqsQueue
      Subscription:
        - Protocol: sqs
          Endpoint:
            "Fn::GetAtt": ["MySqsQueue", "Arn"]
          RawMessageDelivery: 'true'